# Generated by Django 4.2.30 on 2026-04-18 21:02

import apps.content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_character_currency_character_equipped_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('join_mode', models.CharField(choices=[('invitation_only', 'Invitation Only'), ('approval_required', 'Approval Required')], default='invitation_only', max_length=20)),
                ('encumbrance_rules', models.CharField(choices=[('disabled', 'Disabled'), ('simple', 'Simple'), ('variant', 'Variant')], default='simple', max_length=20)),
                ('rule_validation', models.CharField(choices=[('strict', 'Strict'), ('warnings', 'Warnings'), ('permissive', 'Permissive')], default='warnings', max_length=20)),
                ('settings', apps.content.models.JSONField(default=dict, help_text='Custom house rules and settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_session', models.DateTimeField(blank=True, null=True)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
                'unique_together': {('dm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CampaignInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Email if inviting by email', max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='campaigns.campaign')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('pending', 'Pending Approval'), ('left', 'Left'), ('removed', 'Removed')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='campaigns.campaign')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_membership', to='characters.character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_memberships',
                'unique_together': {('campaign', 'player')},
            },
        ),
    ]
