# Generated by Django 4.2.30 on 2026-04-18 22:17

import apps.content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0002_character_currency_character_equipped_items_and_more'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSessionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=200)),
                ('state_data', apps.content.models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_session_states', to='campaigns.campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_states', to='characters.character')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'character_session_states',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('invite', 'Invite'), ('join_request', 'Join Request'), ('combat', 'Combat'), ('session', 'Session')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('payload', apps.content.models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='campaigns.campaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
