# Generated by Django 4.2.30 on 2026-04-20 01:50

import apps.campaigns.models
from django.db import migrations, models


def populate_invite_codes(apps, schema_editor):
    """Assign unique invite codes to any existing campaigns."""
    Campaign = apps.get_model('campaigns', 'Campaign')
    used = set()
    for campaign in Campaign.objects.filter(invite_code=''):
        code = apps.campaigns.models._generate_campaign_code()
        while code in used or Campaign.objects.filter(invite_code=code).exists():
            code = apps.campaigns.models._generate_campaign_code()
        used.add(code)
        campaign.invite_code = code
        campaign.save(update_fields=['invite_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_charactersessionstate_campaignnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='invite_code',
            field=models.CharField(default=apps.campaigns.models._generate_campaign_code, help_text='Short code players can use to join this campaign', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_invite_codes, migrations.RunPython.noop),
    ]
