# Generated by Django 4.2.30 on 2026-04-12 19:02

import apps.content.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hit_die",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "primary_ability",
                    apps.content.models.JSONField(
                        default=list, help_text="Primary ability scores"
                    ),
                ),
                (
                    "saving_throw_proficiencies",
                    apps.content.models.JSONField(
                        default=list, help_text="Saving throw proficiencies"
                    ),
                ),
                ("armor_proficiencies", apps.content.models.JSONField(default=list)),
                ("weapon_proficiencies", apps.content.models.JSONField(default=list)),
                ("tool_proficiencies", apps.content.models.JSONField(default=list)),
                (
                    "skill_choices",
                    models.PositiveIntegerField(
                        default=2, help_text="Number of skills to choose"
                    ),
                ),
                (
                    "spellcasting",
                    apps.content.models.JSONField(
                        default=dict, help_text="Spellcasting information if applicable"
                    ),
                ),
                ("starting_equipment", apps.content.models.JSONField(default=list)),
                (
                    "starting_wealth",
                    apps.content.models.JSONField(
                        default=dict, help_text="Alternative starting wealth"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DamageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("armor", "Armor"),
                            ("weapon", "Weapon"),
                            ("shield", "Shield"),
                            ("tool", "Tool"),
                            ("gear", "Adventuring Gear"),
                            ("mount", "Mount/Vehicle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    apps.content.models.JSONField(
                        default=dict, help_text="Cost in different currencies"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(default=0.0, help_text="Weight in pounds"),
                ),
                ("armor_class", models.PositiveIntegerField(blank=True, null=True)),
                ("dex_bonus_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "strength_requirement",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("stealth_disadvantage", models.BooleanField(default=False)),
                (
                    "damage",
                    apps.content.models.JSONField(
                        default=dict, help_text="Damage dice and type"
                    ),
                ),
                (
                    "properties",
                    apps.content.models.JSONField(
                        default=list, help_text="Weapon properties"
                    ),
                ),
                ("tool_type", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Feat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prerequisite", models.CharField(blank=True, max_length=200)),
                (
                    "ability_score_increase",
                    apps.content.models.JSONField(
                        default=dict, help_text="ASI options"
                    ),
                ),
                (
                    "benefits",
                    apps.content.models.JSONField(
                        default=list, help_text="List of feat benefits"
                    ),
                ),
                (
                    "feat_type",
                    models.CharField(
                        choices=[
                            ("general", "General Feat"),
                            ("fighting_style", "Fighting Style"),
                            ("epic_boon", "Epic Boon"),
                            ("origin", "Origin Feat"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MagicItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("very_rare", "Very Rare"),
                            ("legendary", "Legendary"),
                            ("artifact", "Artifact"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        help_text="Type of item (e.g., 'Wondrous item')", max_length=100
                    ),
                ),
                ("attunement", models.BooleanField(default=False)),
                (
                    "attunement_requirements",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "properties",
                    apps.content.models.JSONField(
                        default=list, help_text="Magic item properties"
                    ),
                ),
                (
                    "charges",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of charges if applicable",
                        null=True,
                    ),
                ),
                ("cursed", models.BooleanField(default=False)),
                ("curse_description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "ability",
                    models.CharField(
                        choices=[
                            ("STR", "Strength"),
                            ("DEX", "Dexterity"),
                            ("CON", "Constitution"),
                            ("INT", "Intelligence"),
                            ("WIS", "Wisdom"),
                            ("CHA", "Charisma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Tiny", "Tiny"),
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                            ("Huge", "Huge"),
                            ("Gargantuan", "Gargantuan"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                (
                    "speed",
                    models.PositiveIntegerField(
                        default=30, help_text="Base walking speed in feet"
                    ),
                ),
                (
                    "darkvision",
                    models.PositiveIntegerField(
                        default=0, help_text="Darkvision range in feet"
                    ),
                ),
                (
                    "ability_score_increases",
                    apps.content.models.JSONField(
                        default=dict, help_text="JSON of ability score bonuses"
                    ),
                ),
                (
                    "traits",
                    apps.content.models.JSONField(
                        default=list, help_text="JSON array of racial traits"
                    ),
                ),
                (
                    "languages",
                    apps.content.models.JSONField(
                        default=list, help_text="JSON array of known languages"
                    ),
                ),
                (
                    "proficiencies",
                    apps.content.models.JSONField(
                        default=dict, help_text="JSON of skill/tool proficiencies"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Species",
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("Abjuration", "Abjuration"),
                            ("Conjuration", "Conjuration"),
                            ("Divination", "Divination"),
                            ("Enchantment", "Enchantment"),
                            ("Evocation", "Evocation"),
                            ("Illusion", "Illusion"),
                            ("Necromancy", "Necromancy"),
                            ("Transmutation", "Transmutation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("casting_time", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                (
                    "components",
                    apps.content.models.JSONField(
                        default=dict, help_text="Verbal, Somatic, Material components"
                    ),
                ),
                ("duration", models.CharField(max_length=100)),
                ("concentration", models.BooleanField(default=False)),
                ("ritual", models.BooleanField(default=False)),
                (
                    "damage",
                    apps.content.models.JSONField(
                        default=dict, help_text="Damage dice and type"
                    ),
                ),
                (
                    "higher_levels",
                    models.TextField(
                        blank=True, help_text="At Higher Levels description"
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="spells", to="content.characterclass"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Tiny", "Tiny"),
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                            ("Huge", "Huge"),
                            ("Gargantuan", "Gargantuan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("creature_type", models.CharField(max_length=50)),
                ("alignment", models.CharField(max_length=50)),
                ("armor_class", models.PositiveIntegerField()),
                ("hit_points", models.PositiveIntegerField()),
                ("hit_dice", models.CharField(max_length=20)),
                (
                    "speed",
                    apps.content.models.JSONField(
                        default=dict, help_text="Different movement speeds"
                    ),
                ),
                ("strength", models.PositiveIntegerField(default=10)),
                ("dexterity", models.PositiveIntegerField(default=10)),
                ("constitution", models.PositiveIntegerField(default=10)),
                ("intelligence", models.PositiveIntegerField(default=10)),
                ("wisdom", models.PositiveIntegerField(default=10)),
                ("charisma", models.PositiveIntegerField(default=10)),
                ("challenge_rating", models.FloatField()),
                ("proficiency_bonus", models.PositiveIntegerField()),
                ("experience_points", models.PositiveIntegerField()),
                (
                    "senses",
                    apps.content.models.JSONField(
                        default=list, help_text="Special senses"
                    ),
                ),
                (
                    "languages",
                    apps.content.models.JSONField(
                        default=list, help_text="Known languages"
                    ),
                ),
                (
                    "special_abilities",
                    apps.content.models.JSONField(
                        default=list, help_text="Special abilities"
                    ),
                ),
                (
                    "actions",
                    apps.content.models.JSONField(default=list, help_text="Actions"),
                ),
                (
                    "bonus_actions",
                    apps.content.models.JSONField(
                        default=list, help_text="Bonus actions"
                    ),
                ),
                (
                    "reactions",
                    apps.content.models.JSONField(default=list, help_text="Reactions"),
                ),
                (
                    "legendary_actions",
                    apps.content.models.JSONField(
                        default=list, help_text="Legendary actions"
                    ),
                ),
                (
                    "condition_immunities",
                    models.ManyToManyField(blank=True, to="content.condition"),
                ),
                (
                    "damage_immunities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="immune_monsters",
                        to="content.damagetype",
                    ),
                ),
                (
                    "damage_resistances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resistant_monsters",
                        to="content.damagetype",
                    ),
                ),
                (
                    "damage_vulnerabilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vulnerable_monsters",
                        to="content.damagetype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="characterclass",
            name="skill_proficiencies",
            field=models.ManyToManyField(
                blank=True, help_text="Available skill choices", to="content.skill"
            ),
        ),
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(default="Player's Handbook 2024", max_length=100),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "languages",
                    apps.content.models.JSONField(
                        default=list, help_text="Languages or language choices"
                    ),
                ),
                (
                    "equipment",
                    apps.content.models.JSONField(
                        default=list, help_text="Starting equipment"
                    ),
                ),
                (
                    "tool_proficiencies",
                    apps.content.models.JSONField(
                        default=list, help_text="Tool proficiencies"
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                ("feature_description", models.TextField()),
                (
                    "skill_proficiencies",
                    models.ManyToManyField(blank=True, to="content.skill"),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "uses",
                    models.CharField(
                        blank=True, help_text="Usage limitations", max_length=50
                    ),
                ),
                (
                    "recharge",
                    models.CharField(
                        blank=True, help_text="Recharge conditions", max_length=50
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="content.characterclass",
                    ),
                ),
            ],
            options={
                "ordering": ["character_class", "level", "name"],
                "unique_together": {("character_class", "name", "level")},
            },
        ),
    ]
