# Generated by Django 4.2.30 on 2026-04-12 23:56

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterclass",
            options={"ordering": ["name"], "verbose_name_plural": "Character Classes"},
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"ordering": ["name"], "verbose_name_plural": "Species"},
        ),
        migrations.AddField(
            model_name="background",
            name="ability_score_increases",
            field=apps.content.models.JSONField(
                default=dict, help_text="JSON of ability score bonuses"
            ),
        ),
        migrations.AddField(
            model_name="background",
            name="origin_feats",
            field=apps.content.models.JSONField(
                default=list, help_text="Available feat choices from this background"
            ),
        ),
        migrations.AddField(
            model_name="background",
            name="skill_choices",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of additional skills to choose"
            ),
        ),
        migrations.AddField(
            model_name="background",
            name="starting_gold",
            field=models.PositiveIntegerField(
                default=0, help_text="Alternative starting gold"
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="subclass_level",
            field=models.PositiveIntegerField(
                default=3, help_text="Level when subclass is chosen"
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="subclass_name",
            field=models.CharField(
                blank=True,
                help_text="What subclasses are called (e.g., 'Domain' for Cleric)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="creature_type",
            field=models.CharField(default="Humanoid", max_length=30),
        ),
        migrations.AddField(
            model_name="species",
            name="lifespan",
            field=models.CharField(
                blank=True, help_text="Typical lifespan description", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="movement_types",
            field=apps.content.models.JSONField(
                default=dict, help_text="Additional movement types (swim, fly, climb)"
            ),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="primary_ability",
            field=apps.content.models.JSONField(
                default=list, help_text="Primary ability scores for multiclassing"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="proficiencies",
            field=apps.content.models.JSONField(
                default=dict, help_text="JSON of skill/tool/armor proficiencies"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="traits",
            field=apps.content.models.JSONField(
                default=list, help_text="JSON array of racial traits with descriptions"
            ),
        ),
    ]
