# Generated by Django 4.2.30 on 2026-04-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_characterclass_options_alter_species_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                default="", help_text="Equipment category", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "Common"),
                    ("uncommon", "Uncommon"),
                    ("rare", "Rare"),
                    ("very_rare", "Very Rare"),
                    ("legendary", "Legendary"),
                    ("artifact", "Artifact"),
                ],
                default="common",
                max_length=20,
            ),
        ),
    ]
