# Generated by Django 4.2.30 on 2026-04-18 21:32

import apps.content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
        ('content', '0003_equipment_category_equipment_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomebrewContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('species', 'Species'), ('class', 'Class'), ('background', 'Background'), ('spell', 'Spell'), ('equipment', 'Equipment'), ('feat', 'Feat'), ('monster', 'Monster'), ('magic_item', 'Magic Item'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('data', apps.content.models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homebrew_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSharingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('use', 'Use in characters')], default='view', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homebrew_permissions', to='campaigns.campaign')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='content.homebrewcontent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_homebrew_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
