# Generated by Django 4.2.30 on 2026-04-18 21:50

import apps.content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_homebrewcontent_contentsharingpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebrewcontent',
            name='dependencies',
            field=apps.content.models.JSONField(default=list),
        ),
    ]
