# Generated by Django 4.2.30 on 2026-05-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_homebrewcontent_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('property_type', models.CharField(choices=[('weapon', 'Weapon Property'), ('mastery', 'Mastery Property')], default='weapon', max_length=10)),
                ('description', models.TextField()),
                ('source', models.CharField(default="Player's Handbook 2024", max_length=100)),
            ],
            options={
                'verbose_name': 'Weapon Property',
                'verbose_name_plural': 'Weapon Properties',
                'ordering': ['property_type', 'name'],
            },
        ),
    ]
