# Generated by Django 4.2.30 on 2026-04-13 00:01

import apps.content.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0002_alter_characterclass_options_alter_species_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("experience_points", models.PositiveIntegerField(default=0)),
                (
                    "strength",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "dexterity",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "constitution",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "intelligence",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "wisdom",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "charisma",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("max_hit_points", models.PositiveIntegerField(default=8)),
                ("current_hit_points", models.PositiveIntegerField(default=8)),
                ("temporary_hit_points", models.PositiveIntegerField(default=0)),
                ("armor_class", models.PositiveIntegerField(default=10)),
                (
                    "saving_throw_proficiencies",
                    apps.content.models.JSONField(
                        default=list, help_text="List of ability names"
                    ),
                ),
                (
                    "equipment",
                    apps.content.models.JSONField(
                        default=list, help_text="Character's equipment"
                    ),
                ),
                (
                    "features",
                    apps.content.models.JSONField(
                        default=list, help_text="Character features and traits"
                    ),
                ),
                (
                    "spells_known",
                    apps.content.models.JSONField(
                        default=list, help_text="Known spells"
                    ),
                ),
                ("personality_traits", models.TextField(blank=True)),
                ("ideals", models.TextField(blank=True)),
                ("bonds", models.TextField(blank=True)),
                ("flaws", models.TextField(blank=True)),
                ("backstory", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this character can be viewed by others",
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.background",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.characterclass",
                    ),
                ),
                (
                    "skill_expertises",
                    models.ManyToManyField(
                        blank=True, related_name="expert_characters", to="content.skill"
                    ),
                ),
                (
                    "skill_proficiencies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="proficient_characters",
                        to="content.skill",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.species",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_prepared", models.BooleanField(default=True)),
                (
                    "is_always_prepared",
                    models.BooleanField(
                        default=False,
                        help_text="Spells that are always prepared (domain spells, etc.)",
                    ),
                ),
                (
                    "spell_level",
                    models.PositiveIntegerField(
                        help_text="Level at which the spell is cast"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_spells",
                        to="characters.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.spell"
                    ),
                ),
            ],
            options={
                "ordering": ["spell__level", "spell__name"],
                "unique_together": {("character", "spell")},
            },
        ),
    ]
