# Generated by Django 4.2.30 on 2026-04-15 00:51

import apps.content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="currency",
            field=apps.content.models.JSONField(
                default=dict, help_text="Character's currency (cp, sp, gp, pp)"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="equipped_items",
            field=apps.content.models.JSONField(
                default=dict, help_text="Currently equipped items by slot"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="equipment",
            field=apps.content.models.JSONField(
                default=list, help_text="Character's equipment items with quantities"
            ),
        ),
    ]
