# Generated by Django 4.2.30 on 2026-04-21 15:58

import apps.content.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_currency_character_equipped_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='tool_proficiencies',
            field=apps.content.models.JSONField(default=list, help_text='List of tool proficiency names'),
        ),
    ]
