# Generated by Django 4.2.30 on 2026-05-02 21:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_add_tool_proficiencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterspell",
            name="source",
            field=models.CharField(
                choices=[("class", "Class"), ("magic_initiate", "Magic Initiate")],
                default="class",
                help_text="Where this spell comes from (class spell list or Magic Initiate feat)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SpellSlotState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_level",
                    models.PositiveIntegerField(
                        help_text="Spell slot level (1–9)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        help_text="Maximum slots available at this level"
                    ),
                ),
                (
                    "used",
                    models.PositiveIntegerField(
                        default=0, help_text="How many slots are currently spent"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_slot_states",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["slot_level"],
                "unique_together": {("character", "slot_level")},
            },
        ),
    ]
