# Generated by Django 4.2.30 on 2026-04-18 21:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0002_character_currency_character_equipped_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('npc_name', models.CharField(blank=True, help_text='Name for NPCs/monsters', max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='Override name shown to players', max_length=200)),
                ('initiative_value', models.IntegerField(default=0)),
                ('hit_points', models.IntegerField(default=0)),
                ('max_hit_points', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True, help_text='Visible to players')),
                ('is_active', models.BooleanField(default=True, help_text='Still in combat')),
                ('turn_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_entries', to='characters.character')),
            ],
            options={
                'db_table': 'initiative_participants',
                'ordering': ['turn_order', '-initiative_value'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Encounter', max_length=200)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('rolling', 'Collecting Initiative Rolls'), ('active', 'Active Combat'), ('paused', 'Paused'), ('concluded', 'Concluded')], default='rolling', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='combat.initiativeparticipant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_trackers', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'initiative_trackers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpellEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spell_name', models.CharField(max_length=200)),
                ('duration_rounds', models.PositiveIntegerField(default=1)),
                ('concentration', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_effects', to='combat.initiativeparticipant')),
                ('initiative_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_effects', to='combat.initiativetracker')),
            ],
            options={
                'db_table': 'spell_effects',
                'ordering': ['duration_rounds'],
            },
        ),
        migrations.AddField(
            model_name='initiativeparticipant',
            name='initiative_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='combat.initiativetracker'),
        ),
    ]
